---
title: "Listing Analysis"
author: "Mihir Bhaskar"
date: "26/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!require("pacman")) install.packages("pacman") # Pacman package has easy load functions (e.g. installs package and then loads if not available)
pacman::p_load(tidyverse, here, stringr, rgdal, leaflet, RColorBrewer)

# set up paths relative to User's Dropbox
if (Sys.info()[["user"]] == "Mihir_Bhaskar") dbpath <- "D:/"
if (Sys.info()[["user"]] == "Sohaib Nasim") dbpath <- "C:/Users/Sohaib/"

base <- paste0(dbpath,"Dropbox/Mayur Vihar Project/Listing Survey/")
raw <- paste0(base,"Data/Raw/")

# Import raw survey data 
raw <- read.csv(paste0(raw,'listing_v1_WIDE.csv'))

# Create simple tab function
tab <- function(x, y){
  
  y <- enquo(y)
  
  x %>% group_by(!!y) %>% summarise(n = n()) %>%
    
    mutate(percent = round((n/sum(n)), 3)) %>% arrange(desc(n))
  
}


```

## R Markdown


```{r basic}

# Block-level summary table 

for (i in 1:10)

raw %>% mutate(has_young_kid = )
  
  group_by(block) %>% summarise(tot_hh = n(), 
                                      need_net = sum(has_mosquito_net == 0),
                                      )


# Number of people per block
tab(raw, block) %>% kable(format.args = list(big.mark = ","), digits = 2, caption = "Number of households per block") %>%
  kable_styling('striped')

# Number of households needing mosquitos per block
need_mosquito <- raw %>% filter(has_mosquito_net == 0)
tab(need_mosquito, block) %>% kable(caption = "Number of households needing mosquito per block") 

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
